---
title: "Introduction to Quarto"
format: html
bibliography: references.bib
---


# Introduction

## About the data

-   Water sample data from Arctic Ocean
-   Data downloaded from the Arctic Data Center: [Tweedie ADC data](https://arcticdata.io/catalog/view/doi:10.18739/A25T3FZ8X)

## Setup

```{r}
#| warning: false

library(readr)
library(here)

```

## Read in data
```{r}
#| warning: false

bg_chem <- read_csv(here("data/BGchem2008data.csv"))
```

# Analysis

## a.  Calculate summary statistics
```{r, echo=FALSE}
#| eval: false

# Print column names
colnames(bg_chem)

# show the data structure
str(bg_chem)

# Show first 6 lines of the data frame
head(bg_chem)

# Get summary of each column
summary(bg_chem)

# Print unique values in a specific column
unique(bg_chem$Date)
```

## b.  Calulate mean Redfield ratio
```{r}
# calculate some means
nitrate <- mean(bg_chem$NO3)
nitrite <- mean(bg_chem$NO2)
amm <- mean(bg_chem$NH4)
phos <- mean(bg_chem$P)
```

## c.  Plot Redfield ratio
```{r}
ratio <- (nitrate + nitrite + amm) / phos
```

Here is the ratio we calculated: `r round(ratio)`

# Conclusion
